Code unification
husarion/rosbot-autonomy pull request #5
Opened 2023-09-13 08:42 UTC by rafal-gorecki

2023-09-19 10:57 UTC, delihus requested changes
Please also add the mecanum variable like here https://github.com/husarion/rosbot-docker/tree/ros2/demo

2023-09-19 10:57 UTC, delihus commented on README.md
> +A step-by-step guide for the ROSbot 2R/PRO to map an unknown environment and navigate autonomously within it from Rviz.
```suggestion
A step-by-step guide for the ROSbot 2R/PRO to map an unknown environment and navigate autonomously within it from RViz.
```

2023-09-19 10:57 UTC, delihus commented on README.md
> +This repository contains the Docker Compose setup for both PC and ROSbot 2R/PRO. You can clone it to both PC and ROSbot 2R/PRO, or use the `./sync_with_rosbot.sh` script to clone it to your PC and ke
```suggestion
This repository contains the Docker Compose setup for both PC and ROSbot 2, 2R and 2 PRO. You can clone it to both PC and ROSbot 2, 2R and 2 PRO, or use the `./sync_with_rosbot.sh` script to clone it to your PC and keep it synchronized with the robot
```

2023-09-19 10:57 UTC, delihus commented on README.md
> +To flash the Micro-ROS based firmware for STM32F4 microcontroller responisble for low-level functionalities of ROSbot 2R/PRO, execute in the ROSbot's shell:
```suggestion
To flash the Micro-ROS based firmware for STM32F4 microcontroller responisble for low-level functionalities of ROSbot 2, 2R and 2 PRO, execute in the ROSbot's shell:
```

2023-09-19 10:57 UTC, delihus commented on README.md
> +### ROSbot 2R/PRO
```suggestion
### ROSbot 2, 2R and 2 PRO 
```

2023-09-19 10:57 UTC, delihus commented on README.md
> +To allow the ROSbot 2R/PRO to localize on a previously created map using AMCL, run:
```suggestion
To allow the ROSbot 2, 2R and 2 PRO to localize on a previously created map using AMCL, run:
```

2023-09-19 10:57 UTC, delihus commented on compose.yaml
> +    image: husarion/rplidar:humble
Please add an exact tag of the `rplidar` docker image.

2023-09-19 10:57 UTC, delihus commented on README.md
>  > **Note:** You do not need to stop the containers to switch between modes.
```suggestion
> [!NOTE]
> You do not need to stop the containers to switch between modes.
```

2023-09-21 14:44 UTC, rafal-gorecki commented on compose.yaml
> +    image: husarion/rplidar:humble
```suggestion
    image: husarion/rplidar:humble-1.0.1-20230427
```

2023-10-17 08:36 UTC, rafal-gorecki commented on .env
> +# - localization - without mapping
```suggestion
# - localization - without mapping (to load map place the `map.yaml` file in the `./maps` path)
```

2023-10-26 10:30 UTC, delihus approved these changes

2023-10-26 10:40 UTC, delihus requested changes

2023-10-26 10:40 UTC, delihus commented on compose.yaml
> -    image: husarion/micro-ros-agent:humble
please use micro ros agent

2023-10-26 10:44 UTC, delihus commented on net.env
> +ROS_DOMAIN_ID=123
Set default ROS_DOMAIN_ID to 0

2023-10-31 08:25 UTC, delihus requested changes

2023-10-31 08:25 UTC, delihus commented on compose.yaml
> +    image: husarion/rplidar:humble-1.0.1-20230427
use stable version husarion/rplidar:humble-1.0.1-20230629-stable

2023-10-31 08:25 UTC, delihus commented on compose.yaml
> +    image: husarion/rosbot:humble-0.6.1-20230712
use stable version

2023-10-31 08:26 UTC, delihus commented on README.md
> +husarion/rosbot:humble-0.6.1-20230712 \
use stable

2023-10-31 09:20 UTC, delihus approved these changes

2023-11-07 08:13 UTC, merged